name: Behavior Bug
description: Report issues with plugin incompatibility or other behavior related issues.
title: "[Bug]: "
labels: [ "status: needs triage", "type: bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug to DartPoet!
        Please fill out the information below to help us understand the issue.
  - type: markdown
    attributes:
      value: |
        Before filling the form fields, please consider the following:
        - Search the [issue tracker](https://github.com/theEvilReaper/DartPoet/issues)
  - type: input
    attributes:
      label: DartPoet version
      description: Please enter the version of DartPoet you are using.
      placeholder: 1.0.0
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
        If you have a screenshot of the bug, please attach it below.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce the bug
      description: Tell us exactly how to reproduce the bug you are experiencing
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code sample
      description: |
        Please create a reproducible sample to show us the bug in action and attach it below between the lines with the backticks.
        This helps us to verify that the bug is valid and prevents us from having to ask you for a sample later.
        
        Without this we will unlikely be able to progress on the issue, and because of that
        we regretfully will have to close it.
        
        **Note**: Please do not upload screenshots of text. Instead, use code blocks
        or the above mentioned ways to upload your code sample.
      value: |
        ```kotlin
        [Paste your code here]
        ```
    validations:
      required: true
