# Thanks paper: https://github.com/papermc/paper/blob/master/.github/workflows/close_invalid_prs.yml
name: Close invalid PRs

on:
  pull_request_target:
    types: [ opened ]

jobs:
  run:
    if: ${{ github.repository != github.event.pull_request.head.repo.full_name && github.head_ref == 'master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        id: "master_branch"
        if: github.head_ref == 'master'
        with:
          comment: |
            Hi there! :wave: This PR is targeting the `master` branch, which is not allowed. Please target the `develop` branch instead. Thanks!